SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS charter_pdf_edits;
DROP TABLE IF EXISTS feedback_responses;
DROP TABLE IF EXISTS ratings;
DROP TABLE IF EXISTS charters;
DROP TABLE IF EXISTS departments;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS feedback;
DROP TABLE IF EXISTS admins;

CREATE TABLE admins (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE departments (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  owner_admin_id INT UNSIGNED DEFAULT NULL,
  name VARCHAR(150) NOT NULL,
  description TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_departments_owner FOREIGN KEY (owner_admin_id) REFERENCES admins (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE charters (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  department_id INT UNSIGNED NOT NULL,
  owner_admin_id INT UNSIGNED DEFAULT NULL,
  title VARCHAR(255) NOT NULL,
  content LONGTEXT NOT NULL,
  file_path VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_charters_department FOREIGN KEY (department_id) REFERENCES departments (id) ON DELETE CASCADE,
  CONSTRAINT fk_charters_owner FOREIGN KEY (owner_admin_id) REFERENCES admins (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE charter_pdf_edits (
  id INT NOT NULL AUTO_INCREMENT,
  charter_id INT UNSIGNED NOT NULL,
  file_path VARCHAR(500) NOT NULL,
  original_name VARCHAR(255) DEFAULT NULL,
  mime_type VARCHAR(100) DEFAULT NULL,
  size_bytes INT DEFAULT NULL,
  submitted_name VARCHAR(255) DEFAULT NULL,
  submitted_email VARCHAR(255) DEFAULT NULL,
  notes TEXT,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT charter_pdf_edits_charter FOREIGN KEY (charter_id) REFERENCES charters (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ratings (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  charter_id INT UNSIGNED NOT NULL,
  owner_admin_id INT UNSIGNED DEFAULT NULL,
  rating TINYINT UNSIGNED NOT NULL,
  comment VARCHAR(500) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_ratings_charter FOREIGN KEY (charter_id) REFERENCES charters (id) ON DELETE CASCADE,
  CONSTRAINT fk_ratings_owner FOREIGN KEY (owner_admin_id) REFERENCES admins (id) ON DELETE SET NULL,
  CONSTRAINT chk_rating_range CHECK (rating BETWEEN 1 AND 5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE feedback_responses (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  charter_id INT UNSIGNED NOT NULL,
  name VARCHAR(150) DEFAULT NULL,
  email VARCHAR(190) DEFAULT NULL,
  contact VARCHAR(50) DEFAULT NULL,
  rating TINYINT UNSIGNED NOT NULL,
  comment VARCHAR(500) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_feedback_charter FOREIGN KEY (charter_id) REFERENCES charters (id) ON DELETE CASCADE,
  CONSTRAINT chk_feedback_rating_range CHECK (rating BETWEEN 1 AND 5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE feedback (
  id INT NOT NULL AUTO_INCREMENT,
  charter_id INT DEFAULT NULL,
  rating INT DEFAULT NULL,
  comment TEXT,
  citizen_name VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  full_name VARCHAR(255) DEFAULT NULL,
  role VARCHAR(50) DEFAULT 'staff',
  department_id INT DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET FOREIGN_KEY_CHECKS = 1;